[package]
name = "http_plugin_rs"
version = "0.0.1-beta.1"
license = "MIT"
description = "Polywrap rust HTTP plugin"
edition = "2021"

include = [
    "src/wrap/*",
    "src/lib.rs",
    "src/mapping.rs"
]

[dependencies]
polywrap_core = { version = "0.1.4-alpha.2" }
polywrap_msgpack = { version = "0.1.4-alpha.2" }
polywrap_plugin = { version = "0.1.4-alpha.4", features = ["implementor"] }
wrap_manifest_schemas = { version = "0.1.4-alpha.2" }
ureq = "2.5.0"
serde = {version = "1.0.145", features = ["derive"]}
base64 = "0.13.0"

[dev-dependencies]
polywrap_client = { version = "0.1.4-alpha.2" }
polywrap_client_builder = { version = "0.1.4-alpha.2" }
