[package]
name = "http_plugin_rs"
version = "0.0.1-beta.2"
license = "MIT"
description = "Polywrap rust HTTP plugin"
edition = "2021"

include = [
    "src/wrap/*",
    "src/lib.rs",
    "src/mapping.rs"
]

[dependencies]
polywrap_client = { path = "../../../rust-client/packages/client" }
ureq = "2.5.0"
serde = {version = "1.0.145", features = ["derive"]}
base64 = "0.13.0"
multipart = "0.17.0"
