"""
This type stub file was generated by pyright.
"""

from abc import ABC
from typing import Any, Dict, Generic, TypeVar
from polywrap_core import Invoker
from polywrap_result import Result

TConfig = TypeVar("TConfig")
TResult = TypeVar("TResult")
class PluginModule(Generic[TConfig, TResult], ABC):
    env: Dict[str, Any]
    config: TConfig
    def __init__(self, config: TConfig) -> None:
        ...
    
    def set_env(self, env: Dict[str, Any]) -> None:
        ...
    
    async def __wrap_invoke__(self, method: str, args: Dict[str, Any], client: Invoker) -> Result[TResult]:
        ...
    


