"""
This type stub file was generated by pyright.
"""

from typing import Generic, TypeVar, Union
from polywrap_core import GetFileOptions, InvocableResult, InvokeOptions, Invoker, Wrapper
from polywrap_manifest import AnyWrapManifest
from polywrap_result import Result
from .module import PluginModule

TConfig = TypeVar("TConfig")
TResult = TypeVar("TResult")
class PluginWrapper(Wrapper, Generic[TConfig]):
    module: PluginModule[TConfig]
    def __init__(self, module: PluginModule[TConfig], manifest: AnyWrapManifest) -> None:
        ...
    
    async def invoke(self, options: InvokeOptions, invoker: Invoker) -> Result[InvocableResult]:
        ...
    
    async def get_file(self, options: GetFileOptions) -> Result[Union[str, bytes]]:
        ...
    
    def get_manifest(self) -> Result[AnyWrapManifest]:
        ...
    


