"""
This type stub file was generated by pyright.
"""

from typing import Generic, Union
from polywrap_core import GetFileOptions, InvocableResult, InvokeOptions, Invoker, Wrapper
from polywrap_manifest import AnyWrapManifest
from polywrap_result import Result
from .module import PluginModule, TConfig, TResult

class PluginWrapper(Wrapper, Generic[TConfig, TResult]):
    module: PluginModule[TConfig, TResult]
    def __init__(self, module: PluginModule[TConfig, TResult], manifest: AnyWrapManifest) -> None:
        ...
    
    async def invoke(self, options: InvokeOptions, invoker: Invoker) -> Result[InvocableResult]:
        ...
    
    async def get_file(self, options: GetFileOptions) -> Result[Union[str, bytes]]:
        ...
    
    def get_manifest(self) -> Result[AnyWrapManifest]:
        ...
    


