"""
This type stub file was generated by pyright.
"""

from typing import Dict, MutableMapping, TypeVar

K = TypeVar("K")
V = TypeVar("V")
class GenericMap(MutableMapping[K, V]):
    _map: Dict[K, V]
    def __init__(self, map: Dict[K, V]) -> None:
        ...
    
    def __getitem__(self, key: K) -> V:
        ...
    
    def __setitem__(self, key: K, value: V) -> None:
        ...
    
    def __delitem__(self, key: K) -> None:
        ...
    
    def __iter__(self): # -> Iterator[K@GenericMap]:
        ...
    
    def __len__(self) -> int:
        ...
    
    def __repr__(self) -> str:
        ...
    


